### ISSUE TITLE
log, exp

### ISSUE THREAD

**Issue by madelynnblue** [ericlagergren/decimal#10]
What's the status of log and exp? They are commented out. Are they broken, not sufficiently tested, too slow?

**Comment by ericlagergren** [comment]
_to wit_ their implementation is not 100% correct. I had previously written both Exp and Log for the initial version of this package, and the functions weren't drop-in ready for the updated version I released a while back.

If I remember correctly (I haven't had much time to work on them this last month or so) they weren't wholly incorrect, but the results weren't accurate to N digits of precision.

So, not a daunting task. Just something I haven't had a whole ton of time to work on lately.
