### ISSUE TITLE
[question] is there func to remove trailing zero?? 

### ISSUE THREAD

**Issue by hiroki-money** [ericlagergren/decimal#101]
As subject, if result is 0.500, I wanna get it as 0.5. Is there such func??

**Comment by ericlagergren** [comment]
Could you give me an example of what you're doing now?

**Comment by hiroki-money** [comment]
@ericlagergren 
For my testing which use calculation using this package, expected data is always string and condition should be same. To do so, zero should be removed. 
For now, after converting Big type to string, I remove zero if it has decimal point.

```
  d := new(decimal.Big)
  //set number or calculate, after that

  str := fmt.Sprintf("%f", d)

  if !strings.Contains(str, ".") {
    return ""
  }

  //remove zero
  return strings.TrimRight(strings.TrimRight(str, "0"), ".")
```

**Comment by ericlagergren** [comment]
Trailing zeros are generally significant, which is why they're retained. See the GDA spec: http://speleotrove.com/decimal/decifaq1.html#tzeros

However, you can do what you want with the `Reduce` method:

```
package main

import (
	"fmt"

	"github.com/ericlagergren/decimal"
)

func main() {
	d, _ := new(decimal.Big).SetString("123.00")
	fmt.Println(d)
	fmt.Println(d.Reduce())
}
```

**Comment by hiroki-money** [comment]
@ericlagergren 
Thank you for your straightforward answer. It's good to know about that decimal specification.

**Comment by hiroki-money** [comment]
I close this issue.
