### ISSUE TITLE
How to limit scale?

### ISSUE THREAD

**Issue by hiroki-money** [ericlagergren/decimal#102]
How can I limit scale when initialize number or result after calculations?
For example, I wanna set scale as 10 and expect result as below.
If I pass number `10.123451234512345` to create decimal.Big object, I wanna get `10.1234512345`. 
In this case, this passed value has scale:15. But I wanna set scale limitation anytime.

**Comment by ericlagergren** [comment]
See `Context`. (On my phone at the moment, I’ll expand more later. But that should start you in the right direction.)

**Comment by hiroki-money** [comment]
Yes, I've already tried to use Context, but nothing happened, I may've made something mistake though.
I wonder, this test [TestDecimal_Format](https://github.com/ericlagergren/decimal/blob/master/format_test.go#L70) indicates that `fmt.Sprintf("%.10f")` is used for display of scale setting.
If `Content` could support scale initially, that format is not needed anymore.

**Comment by hiroki-money** [comment]
I tried this issue using Context to set maxScale, minScale.
As I expected `maxScale` and `minScale` in context seems to be not working now.
Even if scale is set, precision is always prioritized. 
I guess that `Scale` depends on `precision` in context as far as I tried.

I'm sorry if I made a mistake.

**Comment by ericlagergren** [comment]
Okay, so to clarify you want to limit the number of digits after the decimal point? Yes, `fmt.Sprintf("%.10f", x)` will allow you to print `x` with 10 digits after the decimal point.

`Quantize` will allow you to change the number of digits after the decimal point.

```
package main

import (
	"fmt"

	"github.com/ericlagergren/decimal"
)

func main() {
	x, _ := new(decimal.Big).SetString("10.123451234512345")
	fmt.Printf("%0.10f\n", x)
	x.Quantize(10)
	fmt.Println(x)
}
```

**Comment by hiroki-money** [comment]
@ericlagergren 
I got it thanks to it. Thus this issue is closed.
