### ISSUE TITLE
_testdata links pointing to themselves

### ISSUE THREAD

**Issue by kentquirk** [ericlagergren/decimal#103]
I just did a `go get` of this repository, and then this command fails:

```
gopkgs -format '{{.Name}};{{.ImportPath}}'
```

(That command is used by VS Code to capture installed package information.)

The problem is that the recently-added `_testdata` symlinks in misc and math are pointing to themselves, which causes infinite loops in directory-traversing code. Were they intended to point to `_testdata` in the parent directory?

**Comment by ericlagergren** [comment]
Thanks!
