### ISSUE TITLE
Float64() returns ok=false -- true expected

### ISSUE THREAD

**Issue by pennersr** [ericlagergren/decimal#105]
In the following example, `Float64()` returns `ok=false` whereas I would have expected `true` here.

```
	b := &decimal.Big{}
	b.SetString("6190.000000000000")
	_, ok := b.Float64()
	if !ok {
		log.Fatalf("6190 should fit in a float just fine")
	}
```

**Comment by ericlagergren** [comment]
Hmmm, yeah. While it _does_ return the correct float result (6190.000...), the 'false' is definitely wrong. I suppose if the decimal, `x`, is an integer and `x <= 1<<53` we can return it directly as a float64.

The case that was hit in your example was meant for something like `6190.12345678912398` which can't be exactly represented as a float (you'd get `6190.12345678912425` instead).
