### ISSUE TITLE
decimal/benchmarks/pi_test.go broken by changes to dnum

### ISSUE THREAD

**Issue by dr2chase** [ericlagergren/decimal#108]
decimal/benchmarks/pi_test.go no longer builds because of changes to github.com/apmckinlay/gsuneido/util/dnum  package.

```
cp pi_test.go pi_test-.go
sed -e '1,$s/NewDnum(false, \([0-9]*\), 0/FromInt(\1/' < pi_test-.go > pi_test.go
```

**Comment by ericlagergren** [comment]
I'll take a look. Thank you for letting me know!

**Comment by dr2chase** [comment]
FYI, s/dnum.Cmp/dnum.Compare/
I think dnum is undergoing some cleanup.

**Comment by ericlagergren** [comment]
Awesome. If you don't mind me asking, what're you using the library for? It's super interesting to see what people use it for.

**Comment by dr2chase** [comment]
You'll be sad(ish).  I work on the Go compiler, we have an inadequate (in my opinion) set of benchmarks, so if anyone with a mildly popular project has also written benchmarks, and I find them, and they are not too much of a duplicate of something we've already got (and not too noisy, not too slow, etc) then I incorporate them into the list of benchmarks to run.  See
https://github.com/golang/go/wiki/Benchmarks

I get + build + run/test then using https://github.com/dr2chase/bent (this is Google code under my account to avoid the annoying problem of "where do we put this"; I need to get the copyrights etc in place).

This may or may not lead to more attention paid to whether your code runs well and/or compiles under the development version of Go.  The benchmark runner also includes a run-tests option.

**Comment by ericlagergren** [comment]
That's still pretty neat. Glad to see it could be of help!
