### ISSUE TITLE
JSON Marshal on nil pointer panics

### ISSUE THREAD

**Issue by aarondl** [ericlagergren/decimal#110]
Given this example program:

```go
package main

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/ericlagergren/decimal"
)

type Struct struct {
	*decimal.Big
}

func main() {
	var s Struct
	b, err := json.Marshal(s)
	if err != nil {
		fmt.Println("err:", err)
		os.Exit(1)
	}

	fmt.Printf("%s\n", b)
}
```

The output produced is:

```text
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x4cfbf5]

goroutine 1 [running]:
encoding/json.(*encodeState).marshal.func1(0xc000053e98)
	/usr/local/go/src/encoding/json/encode.go:301 +0x9a
panic(0x4f3520, 0x5e4620)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/ericlagergren/decimal.(*Big).IsFinite(...)
	.../src/github.com/ericlagergren/decimal/big.go:826
github.com/ericlagergren/decimal.(*Big).Precision(...)
	.../src/github.com/ericlagergren/decimal/big.go:962
github.com/ericlagergren/decimal.(*Big).MarshalText(0x0, 0x4091d3, 0x4f4ba0, 0x513160, 0x513100, 0x7f4d5b884060)
	.../src/github.com/ericlagergren/decimal/big.go:908 +0x55
encoding/json.textMarshalerEncoder(0xc0000b2000, 0x513160, 0x0, 0x19, 0xc000050100)
	/usr/local/go/src/encoding/json/encode.go:486 +0xee
encoding/json.(*encodeState).reflectValue(0xc0000b2000, 0x513160, 0x0, 0x19, 0x4f0100)
	/usr/local/go/src/encoding/json/encode.go:333 +0x82
encoding/json.(*encodeState).marshal(0xc0000b2000, 0x513160, 0x0, 0x100, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:305 +0xf4
encoding/json.Marshal(0x513160, 0x0, 0xc00000a280, 0xc00000a260, 0xc00000a240, 0xc00000a220, 0xc00000a200)
	/usr/local/go/src/encoding/json/encode.go:160 +0x52
main.main()
	.../lol.go:17 +0x48
exit status 2
```

I was going to correct this and PR it, but it appears there's no `MarshalJSON` implementation, only a `MarshalText`. I think for JSON marshalling it should interpret nil pointers correctly for both encoding and decoding. This kind of check is sufficient:

```go
func (x *Big) MarshalJSON() ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}
```

The issue that spawned this issue is here: https://github.com/volatiletech/sqlboiler/issues/404

**Comment by andradei** [comment]
The problem, in this case, seems to be all cases where `func (x *Big) ...` doesn't check `x == nil` before calling `x.OneOfItsMethods(...)`. Either that or `MarshalText` (and maybe `UnmarshalText`) not checking `x == nil`.

**Comment by andradei** [comment]
@aarondl I made a little program that shows the issue, and it looks like the problem in in Unmarshal as well:

```go
package main

import (
	"encoding/json"
	"fmt"

	"github.com/ericlagergren/decimal"
)

type myType struct {
	*decimal.Big
}

func main() {
	b, _ := new(decimal.Big).SetString("111001.22")
	m1 := myType{b}

	fmt.Printf("m1 struct: %#v\n", m1)

	m1Json, err := json.Marshal(m1)
	if err != nil {
		panic(fmt.Sprint("error 1:", err))
	}

	fmt.Printf("m1 json: %#v\n", string(m1Json))

	var m2 myType
	err = json.Unmarshal(m1Json, &m2)
	if err != nil {
		panic(fmt.Sprintf("error 2:", err))
	}

	fmt.Printf("m2 struct: %#v\n", m2)
}
```

The output is:

```
m1 struct: &decimal.Big{Context:decimal.Context{MaxScale:0, MinScale:0, Precision:0, Traps:0x0, Conditions:0x0, RoundingMode:0x0, OperatingMode:0x0}, unscaled:big.Int{neg:false, abs:big.nat(nil)}, compact:0xa95fda, exp:-2, precision:8, form:0x0}
m1 json: "\"111001.22\""
m2 struct: %!v(PANIC=runtime error: invalid memory address or nil pointer dereference)
```

Could you edit the issue to including Unmarshling too?

**Comment by ericlagergren** [comment]
A couple of things.

First off, `MarshalText` _should_ return the string `"<nil>"` if `x == nil`. I will make that fix.

Unfortunately—even after adding the `x == nil` check—embedding won't do exactly what you want: (https://play.golang.org/p/GHIAH1t2cSd). You also run into a similar issue with unmarshaling: (https://play.golang.org/p/gXR-GwVhK6w).

This is more an issue (for lack of a better word) with Go than it is this package.

In fact, I can't make unmarshaling on an embedded nil pointer work even if I wanted to since there's no way to set the embedded field to a newly-allocated `Big` (the encoding/json package normally does this).

At any rate, I'd caution against using `NullXXX` in a JSON API. Isn't it just for database use?

**Comment by andradei** [comment]
@ericlagergren > At any rate, I'd caution against using NullXXX in a JSON API. Isn't it just for database use?

This is a good point. Given the limitations in the combination of struct embedding and JSON encoding/decoding, I'd say it will be better for me to avoid `NullXXX` when using JSON.

The issue also arose when not embedding, though the end error was a little different. But I get the picture.

Thank you.

**Comment by ericlagergren** [comment]
I'll push the MarshalText change by this weekend (or, if you need it sooner you're more than welcome to add it!) I think. Sorry about the issue, though. Just a weird Go edge case.

**Comment by GalGavu** [comment]
@ericlagergren any update? :)
