### ISSUE TITLE
go.mod requires a patch version

### ISSUE THREAD

**Issue by djmarcin** [ericlagergren/decimal#111]
Currently go modules just grabs the latest commit because your SemVer tags don’t include a patch version. Changing the tags from v3.1 to v3.1.0 should fix it, I think.

**Comment by djmarcin** [comment]
It looks like modules also requires for major versions 2+ that the module path and package import path contain the major version number, e.g. ‘module github.com/ericlagergren/decimal/v3’, so this might be a bit more involved :-/

**Comment by kardianos** [comment]
I can confirm, if you release as a v3 library, your go.mod file would need to start with `module github.com/ericlagergren/decimal/v3` and your semver tag would need to be something like `v3.1.0`.

However, if this is the first getable tag for go modules, maybe just reset back to `v1.3.1` and keep the module name as is?

**Comment by ericlagergren** [comment]
Hm. So, I've already released v3.2 but I _haven't_ included go.mod in a release so yet (14 commits separate v3.2 from HEAD).

Is it possible to release v.3.3.0 with a `v3/` directory that contains the requisite go.mod file?

Or, should I bump to v4.0?

**Comment by kardianos** [comment]
You don't need, but can use, a sub-directory. I would avoid it.

The v3 at the end of the module path will be ignored by the older versions that have been patched. So you can safely make the module path end in a `/v3` tag v3.3.0 in place (no moving files).

I don't see a reason to bump to v4 unless you have some breaking change, which it doesn't look like you have.

**Comment by ericlagergren** [comment]
Awesome, thanks @kardianos.

**Comment by ericlagergren** [comment]
(I guess this means I should go and re-read the modules docs.)

**Comment by kardianos** [comment]
Readme (current version) might be out of date.

**Comment by ericlagergren** [comment]
Thanks for letting me know. Will fix that. 

Envoyé de mon iPhone
