### ISSUE TITLE
Go Modules and v3.3.0 is breaking build

### ISSUE THREAD

**Issue by andradei** [ericlagergren/decimal#112]
After the change in #111 my build broke. When compiling, it tries to find the latest version as package, and not a module (notice the v0.0.0-20181210064008-7f7cf8a362e5, the last part being the hash for tag v3.3.0):

```
...
go: finding github.com/ericlagergren/decimal latest
go: downloading github.com/ericlagergren/decimal v0.0.0-20181210064008-7f7cf8a362e5
...
```

And eventually can't with the following error:

```
build [my project]: cannot find module for path github.com/ericlagergren/decimal
```

My `go.mod` was updated to have `require github.com/ericlagergren/decimal/v3 v3.3.0` and my import paths were modified accordingly to `import github.com/ericlagergren/decimal/v3`.

Trying a work-around: If I try to put the lastest version (tag v3.3.0) like so in my `go.mod`

```
require github.com/ericlagergren/decimal v0.0.0-20181210064008-7f7cf8a362e5
```

I get the following error: 

```
go: github.com/ericlagergren/decimal@v0.0.0-20181210064008-7f7cf8a362e5: go.mod has post-v0 module path "github.com/ericlagergren/decimal/v3" at revision 7f7cf8a362e5
```

So `go mod` knows this is a Go Module with `v3` in its name and won't let me.

The only solution I found right now was to use v3.2 by its commit hash:

```
go get github.com/ericlagergren/decimal@2a58211

cat go.mod
...
require github.com/ericlagergren/decimal v0.0.0-20180316053741-2a5821154e15
...
```

That compiled successfully.

Would this be an issue with how `go.mod` on this project was setup? Would it be an issue with `go mod` itself (since it is still experimental)? It surely can be an issue with my `go.mod` too, but I've tried all sorts of fixes at this point, hence why I'm opening this issue. I recreated my `go.mod`, I ran `go clean -modcache`, etc. Nothing worked except going back to v3.2.

**Comment by jmartin127** [comment]
I am experiencing the same issue when trying to use SQLBoiler, which depends on this package.

**Comment by Atrox** [comment]
I've got the same problem. I think the way to go is:

- create new v3.3.1 without go.mod /v3 suffix
- create new v4.0.0 with go.mod /v4 suffix

This causes no breaking changes and with v4 you start to follow the standard

**Comment by ericlagergren** [comment]
I know it's a simple change but I don't know if I'll have time to implement & test it out for a few days at least. PRs are always welcome. :) Apologies for the goof up.

**Comment by Dexus** [comment]
hey, is there any progress or when will this issue fixed? Its pritty shit if you have to switch to the old days again to use this lib. Modules should today work...
