### ISSUE TITLE
Float64() returns unexpected value for negative integers when scale = 0

### ISSUE THREAD

**Issue by lokeshj** [ericlagergren/decimal#114]
Hi,

I'm not sure if I'm doing something wrong here. I have a simple test case 
```go
	val := decimal.New(-1, 0)
	f, _ := val.Float64()

	fmt.Println(val)
	fmt.Println(f)
```
Output:
```
-1
-1.8446744073709552e+19
```

I was expecting it to print `-1` in both the lines. 

Also, if I change the scale to 1:
```go
val := decimal.New(-1, 1)
f, _ := val.Float64()

fmt.Println(val)
fmt.Println(f)
```
It correctly prints `-0.1` in both lines.

**Comment by ericlagergren** [comment]
Thanks!
