### ISSUE TITLE
rounding with lossless operations

### ISSUE THREAD

**Issue by madelynnblue** [ericlagergren/decimal#12]
Some operations like addition can be performed without loss of precision. What are your thoughts about instead respecting the context's precision during these operations, which would round after all operations? A precision of 0 would keep the current behavior to not round.

For example, with a precision of 3:

100 + 0.1 = 100

Benefits to this approach:

- Some algorithms for computing pow involve repeated squaring. Given an already large input, after ~10 iterations the number of digits is crazy high and it takes a few seconds per multiplication. Restricting these operations to some known precision can prevent this kind of problem. (See https://github.com/cockroachdb/cockroach/commit/b7c11c8bfe2de7365d1c585ae4c20bf28570ea81 for example.)
- The test suite at speleotrove requires this, and I think would make a good addition to this package.

**Comment by ericlagergren** [comment]
For those operations I manually round. 

My only issue with implementing this is whether it's intuitive or not. I'm also not aware of another major library that rounds lossless operations like addition. I'm open to it.

**Comment by madelynnblue** [comment]
Python does:

```
from decimal import *
getcontext().prec = 3
print Decimal('100') + Decimal('0.1')
getcontext().prec = 4
print Decimal('100') + Decimal('0.1')
print Decimal('12345')
print getcontext().create_decimal(12345)
print Decimal('12345') + Decimal('0')
```

Output:

```
100
100.1
12345
1.234E+4
1.234E+4
```

**Comment by ericlagergren** [comment]
hmmm... well, if it's in speletrove's spec then I suppose I'll have to go with it!

**Comment by madelynnblue** [comment]
There are other options like having two precision fields: one for lossy operations and one for lossless operations. This would allow the API to stay the same with an option to enhance when desired. I'm less a fan of this, but it is a possibility.

The other difficulty comes along because in python there's a global context, and it is consulted when performing operations. Here we have 2 decimals and are performing an operation. What if they have differing precisions? Which one to use? Or do we use the precision of the result decimal? Probably that, I guess.

**Comment by ericlagergren** [comment]
I'm on my phone so Ill expand when I get home but convention is to use the
receiver's precision.

**Comment by ericlagergren** [comment]
I'm opposed to having two fields: that seems a bit unwieldy, not to mention adding extra space (well, possibly—unsure about alignment).

like my previous comment said, the receiver dictates the precision, rounding mode, etc.

I'm fine with having rounding, especially since speletrove's spec says:

> The result is then rounded to precision digits if necessary, counting from the most significant digit of the result.

so, sounds good to me!

**Comment by ericlagergren** [comment]
@mjibson is this something you would like to contribute? curious whether I need to put this on my radar or not.

**Comment by madelynnblue** [comment]
After doing some research I've decided to go another way, so I'm not going to be working on this feature now, no. I'll leave this open if you're planning on working on it.

**Comment by ericlagergren** [comment]
another way with cockroachdb?

Anyway thanks for the modf PR. Cheers.
