### ISSUE TITLE
Parameter list - version differences

### ISSUE THREAD

**Issue by PumpkinSeed** [ericlagergren/decimal#126]
There is some issue in the parameter lists in the decimal/internal/arith package. The Sub64 function has an extra parameter in decimal/internal/arith/arith_1_11.go so when the decimal/big_ctx.go call it in case of 1.11 version will throw a build error.

**Comment by LoganK** [comment]
Trying to push a fix in Pull #125

**Comment by ericlagergren** [comment]
Will fix this ASAP.

Also, now that this package uses modules please use specific versions instead of relying on master.

I understand not everybody uses modules, so I try to make sure master isn’t broken. But things happen. :)
