### ISSUE TITLE
Postgres driver included as transitive dependency when using Go modules

### ISSUE THREAD

**Issue by shabbyrobe** [ericlagergren/decimal#128]
When I run `go get` in a project using `github.com/ericlagergren/decimal`, I see unexpected transitive dependencies in my `go.mod`:

```
module example.com/thingy

go 1.12

require (
	github.com/ericlagergren/decimal v0.0.0-20190408093654-b4c50b82c335
	github.com/lib/pq v1.1.0 // indirect
)
```

I'm not using postgres in this project, I just need arbitrary precision decimals, so I'd prefer that this wasn't appearing in my `go.mod` as it will be confusing to other developers (and probably "future me" too).

**Comment by ericlagergren** [comment]
Hm. I might have to make the SQL subpackage its own module then.

Ideally, I’ll just deprecate it then remove it when the decimal decomposition proposal is merged.

**Comment by shabbyrobe** [comment]
Thanks for the quick reply!

I have a similar problem with one of my own repos so I've been trying to flush out exactly what the best way of dealing with this from the mountain of closed, diverted, redirected or atrophied issues on the subject on the golang github... it occurs to me that I probably don't actually even know what the right thing to do here is!

Is multiple modules in the one repository actually a supported thing at the moment, or is it likely to break for other people in weird ways?

**Comment by ericlagergren** [comment]
Yeah, nested modules is supported. I think the Go team was looking at doing that for some of its repos. Or maybe the did already.

The next version I release is going to be 4.0, so I might just delete it and avoid any weird module pains.

**Comment by shabbyrobe** [comment]
Oh you mean just delete the `go.mod` entirely for the time being? That won't cause me any trouble but could it cause trouble for others? Or is that sidestepped by the major version bump?

**Comment by ericlagergren** [comment]
Sorry, “it” meaning the sql/ subpackage.

**Comment by kardianos** [comment]
Support for the decomoser interface is in master in database/sql.

**Comment by ericlagergren** [comment]
Will close this once I've deleted the sql/ package, likely when I (finally) cut v4.

**Comment by lotodore** [comment]
This has been fixed by https://github.com/ericlagergren/decimal/pull/183 so in my opinion could be closed.

**Comment by shabbyrobe** [comment]
Agreed. Thanks!
