### ISSUE TITLE
Inconsistent comments

### ISSUE THREAD

**Issue by yarco** [ericlagergren/decimal#133]
https://github.com/ericlagergren/decimal/blob/ac8aeb47a55cc0f667ba2f6ab469753b5b682b22/big.go#L948

The comment to `Quantize` is misleading. You need to set 

> Rounding towards zero
> round towards zero (or truncate, or round away from infinity): y is the integer part of x, without its fraction digits.
https://en.wikipedia.org/wiki/Rounding#Rounding_towards_zero
for the method to behave as Truncate

**Comment by ericlagergren** [comment]
Yes, thank you for pinging me about this. After I made the change to add the docs I realized the mistake, but forgot to fix it.

Would you mind adding those docs? Would be appreciated!
