### ISSUE TITLE
SetRat can modify the input argument

### ISSUE THREAD

**Issue by yarco** [ericlagergren/decimal#138]
```
// SetRat sets z to to the possibly rounded value of x and return z.
func (z *Big) SetRat(x *big.Rat) *Big {
	if x.IsInt() {
		return z.Context.round(z.SetBigMantScale(x.Num(), 0))
	}
	var num, denom Big
	num.SetBigMantScale(x.Num(), 0)
	denom.SetBigMantScale(x.Denom(), 0)
	return z.Quo(&num, &denom)
}
```

`d.Denom()` can potentially modify x. If many goroutines have handles to `x` we can have a race

**Comment by ericlagergren** [comment]
Thanks! Looks like I'll have to check whether `x.IsInt` first, then if so use my own constant.

**Comment by ericlagergren** [comment]
Have you experienced races in practice? The call to `x.IsInt` should catch the case where `x.Denom` materializes the denominator.

**Comment by yarco** [comment]
No, I've not experienced races in practice. Spotted this by chance. To be on the safe side I clone my input number using `new(big.Rat).Set(number)` and then pass it into `SetRat`

**Comment by ericlagergren** [comment]
Okay. Because the code is checking whether the denominator is 1 (via IsInt) prior to calling Denom, the code is race-free.

I appreciate you opening the issue!
