### ISSUE TITLE
problem while go get decimal the way the readme suggests.

### ISSUE THREAD

**Issue by morriswinkler-simple** [ericlagergren/decimal#14]
I got a recent go 1.7.4

```
go get github.com/EricLagergren/decimal
```

resolves into the following message

```
package github.com/EricLagergren/decimal
	imports github.com/ericlagergren/decimal/internal/arith: use of internal package not allowed
package github.com/EricLagergren/decimal
	imports github.com/ericlagergren/decimal/internal/arith/checked: use of internal package not allowed
package github.com/EricLagergren/decimal
	imports github.com/ericlagergren/decimal/internal/arith/pow: use of internal package not allowed
package github.com/EricLagergren/decimal
	imports github.com/ericlagergren/decimal/internal/c: use of internal package not allowed
```

the way it works is 

```
go get github.com/ericlagergren/decimal
```

please update your readme

**Comment by ericlagergren** [comment]
thanks

**Comment by morriswinkler-simple** [comment]
No problem, by the way, i have real difficulties on how to figure out how to round to n digits of the fraction of a decimal. 

In the moment I use 

```
	if priceTotal.Scale() > 2 {
		// round to two digits of precision if we get ever something like 0.001
		round := int32(priceTotal.Prec() - (int(priceTotal.Scale()) - 2))
		priceTotal.Round(round)
	}
```
Is it just my stupidity or is this the way to go ?

**Comment by ericlagergren** [comment]
Yeah, it's the way to go for now. I know it's unwieldy—it's a bit of an artifact of decimal libraries. Most specs only have the concepts of _precision_ and _scale_, neither of which explicitly refer to the trailing digits.

What are you rounding for? I'm considering something like, e.g., a RoundTo function which rounds toN N decimal places.

**Comment by morriswinkler-simple** [comment]
I am Rounding to two digits of the fraction part, Big.RoundScale would be more understandable ( at least for me). The case I use it for is connected to prices, so at some point, I always need to round the fraction part to one hundredth ( eq 0.00). From my perspective, it would be convenient to be able to explicitly round the scale part. 

How is it going with the effort to get that into the golang library, have you found a reviewer from withing google ?

**Comment by ericlagergren** [comment]
> From my perspective, it would be convenient to be able to explicitly round the scale part.

Same.

> From my perspective, it would be convenient to be able to explicitly round the scale part.

Eh. I have not found a reviewer yet. adg (I think) created an issue a while back about whether more libraries should be added to exp/, so it's not looking good tbh.
