### ISSUE TITLE
performance benchmark does not seem to match published benchmark

### ISSUE THREAD

**Issue by k1ng440** [ericlagergren/decimal#140]
Hello,
I am benchmarking with following

```go
package misc_test



import (
	"github.com/ericlagergren/decimal"
	shopdecimal "github.com/shopspring/decimal"
	"testing"
)

func BenchmarkDecimalByShopspring(b *testing.B) {

	for n := 0; n < b.N; n++ {
		_, _ = shopdecimal.NewFromString("1294.300303030580521596")
	}


}


func BenchmarkDecimalByEriclagergren(b *testing.B) {
	for n := 0; n < b.N; n++ {
		big := new(decimal.Big)
		big.SetString("1294.300303030580521596")
	}
}
```

Test result:
```
BenchmarkDecimalByShopspring-12       	 2251071	       535 ns/op
BenchmarkDecimalByEriclagergren-12    	 1771297	       673 ns/op
PASS
```

**Comment by ericlagergren** [comment]
I don't know where those benchmarks are from. There are only two posted benchmarks (https://github.com/ericlagergren/decimal/blob/2c3e3e1ef942ac4ca58d18a6bc27a0c784d621e8/benchmarks/doc.go): pi and mandelbrot.

At any rate:

1. I'm not sure what benchmarking SetString demonstrates, it's a rather inexpensive operation cf division, etc.
2. My benchmarks need to be updated to Go 1.13, newer library versions, etc.

**Comment by ericlagergren** [comment]
Unless there's anything else, I'm going to close this as there's nothing here to fix.
