### ISSUE TITLE
Bad Cmp result

### ISSUE THREAD

**Issue by rif** [ericlagergren/decimal#15]
Hi, I just switched from doing floating point to you excellent decimal lib. 

In the test I reached a point where I have this:
t.Log(result.Cost.Cmp(expected.Cost), expected.Cost.String(), result.Cost.String())

with this wrong result:
1 2701 2701
The expected cost is created as decimal.New(2701, 0) and the result comes from the tested function. 
If you need other info please let me know!

Thanks,
-rif

**Comment by rif** [comment]
I printed the internals if it helps:
```
RESULT: 9223372036854775807, scale: 5, ctx: {precision:0 mode:0}, form: 1, unscaled: {false [270100000]}
EXPECTED: compact: 2701, scale: 0, ctx: {precision:0 mode:0}, form: 1, unscaled: {false []}
```

Some other values with similar problem:
```
RESULT: compact: 9223372036854775807, scale: 5, ctx: {precision:0 mode:0}, form: 1, unscaled: {false [181050000]}
EXPECTED: compact: 18105, scale: 1, ctx: {precision:0 mode:0}, form: 1, unscaled: {false []}
```

**Comment by ericlagergren** [comment]
can you reproduce this on the dev branch?

**Comment by ericlagergren** [comment]
I ask because I think the fix is on the dev branch atm.

**Comment by rif** [comment]
I confirm  that the dev branch fixes the first problem (the one with 2701) but the second one with 1810.5 is NOT fixed. Also I got two other tests that fail: before the result was 0.3 after a Round(9) and now it's 0.300000001

**Comment by ericlagergren** [comment]
could you post minimal repros for the bugs?

**Comment by rif** [comment]
unfortunately not, I will try to push a test on your dev branch.

**Comment by ericlagergren** [comment]
okay. I can't begin debugging this until I have a couple test cases to look at.

**Comment by rif** [comment]
Would this type of test help?

```go
func TestBig_CmpUnscale(t *testing.T) {
	b1 := &Big{compact: 9223372036854775807, scale: 5, ctx: Context{precision: 0, mode: RoundingMode(0)}, form: 1, unscaled: *new(big.Int).SetInt64(181050000)}
	b2 := &Big{compact: 18105, scale: 1, ctx: Context{precision: 0, mode: RoundingMode(0)}, form: 1, unscaled: *new(big.Int).SetInt64(0)}
	if b1.Cmp(b2) != 0 {
		t.Errorf("failed comparing %v with %v: %v", b1, b2, b1.Cmp(b2))
	}
}
```

**Comment by rif** [comment]
So I added this test on the dev branch and on my machine there are three tests failing:

```
--- FAIL: TestBig_Cmp (0.00s)
	decimal_test.go:170: #10: wanted 0, got -1
--- FAIL: TestBig_IsBig (0.00s)
	decimal_test.go:191: #4: wanted true, got false
--- FAIL: TestBig_CmpUnscale (0.00s)
	decimal_test.go:569: failed comparing 1810.5 with 1810.5: 1
```

**Comment by ericlagergren** [comment]
ahhh I see the problem, thanks.

**Comment by rif** [comment]
I confirm that the above issues are fixed but now I encountered:
```
t.Log(x.String(), y.String(), x.Cmp(y))
0.1         0.016666666666666666          -1
```

**Comment by rif** [comment]
```
x = compact: 1000000000000000, scale: 16, ctx: {16 0}, form: form(1), unscaled: {false []}
y = compact: 16666666666666666, scale: 18, ctx: {0 0}, form: form(1), unscaled: {false []}
x.String() = 0.1
y.String() =  0.016666666666666666
x.Cmp(y) = -1
```

**Comment by ericlagergren** [comment]
I actually think a bad test case is why this is goofed.

**Comment by ericlagergren** [comment]
yeah, this https://github.com/ericlagergren/decimal/commit/63aaff26e9ab8a32b0e6e5ad433a91df837de379#diff-e035ddc6d9eb583a74a989c446aad535R168 was causing my tests to be wrong so the resulting code was wrong.

**Comment by ericlagergren** [comment]
@rif if this is still an issue feel free to reopen.

**Comment by rif** [comment]
All good on my side now. Thanks again!

**Comment by ericlagergren** [comment]
Thank you!
