### ISSUE TITLE
Separate benchmarks to their own package?

### ISSUE THREAD

**Issue by bojanz** [ericlagergren/decimal#150]
I just tried to use this package via go mod, and was surprised to see that it pulls in cockroachdb/apd, shopspring/decimal, and all other libraries that are benchmarked. That feels a bit wasteful. Would it make sense to move benchmarks to their own package to trim down the dependency list?

**Comment by ericlagergren** [comment]
This is a good idea, thanks.

**Comment by bojanz** [comment]
Is there anything I can do to push this along? Or is this blocked on v4?

I am preparing a currency handling package, and using this library instead of cockroachdb/apd is giving me noticeably better performance (on top of a more friendly API), but the go mod issues are giving me pause. Of course, my own API doesn't expose the decimal implementation, so it will be safe to swap out later without breakage.

**Comment by ericlagergren** [comment]
If you want to submit a PR that would be fantastic! I haven't had a moment to sit down and do it yet, sorry about that.

**Comment by bojanz** [comment]
Apologies, managed to lose track of this.

I tried doing a "go mod init github.com/ericlagergren/decimal/benchmarks" in the benchmarks directly and running "go mod tidy" both there and in the root directory. This cleans up the root directory as expected, but the go.mod in benchmarks/ is incomplete (e.g. missing cockroachdb/apd) for some reason:

```
module github.com/ericlagergren/decimal/benchmarks

go 1.14

require (
	github.com/apmckinlay/gsuneido v0.0.0-20200514163306-0630c2de03b0 // indirect
	github.com/ericlagergren/decimal v0.0.0-20191206042408-88212e6cfca9 // indirect
	github.com/shopspring/decimal v1.2.0 // indirect
)
```

I also get the following warning when running "go mod tidy" in the benchmarks directory:
```
github.com/ericlagergren/decimal/benchmarks: ambiguous import: found package github.com/ericlagergren/decimal/benchmarks in multiple modules:
	github.com/ericlagergren/decimal/benchmarks (/Users/bojanz/dev/go/decimal/benchmarks)
	github.com/ericlagergren/decimal v0.0.0-20191206042408-88212e6cfca9 (/Users/bojanz/go/pkg/mod/github.com/ericlagergren/decimal@v0.0.0-20191206042408-88212e6cfca9/benchmarks)
```

I might be using go mod incorrectly...

**Comment by bojanz** [comment]
Hm, I seem to have misunderstood how go mod works. I ran go mod tidy && go mod vendor and it didn't mention or download the benchmark dependencies. Which makes sense, I don't import the benchmarks package.

Sorry for wasting your time.
