### ISSUE TITLE
SetString("3,60") returns a NaN instead of an error

### ISSUE THREAD

**Issue by bojanz** [ericlagergren/decimal#153]
I've converted bojanz/currency from cockroachdb/apd to this package, and the tests are green:
https://github.com/bojanz/currency/commit/2a46a5c72473f6305809b03ac851e8bc7fffe95c

However, I was surprised by one difference in behavior between the two packages:
```
result, ok := new(decimal.Big).SetString(n)
```
If I pass "3,60" to SetString(), which is a string with an invalid decimal separator, instead of getting nil, false I get NaN, true.

This forces me to check for NaN every time:
```
if !ok || result.IsNaN(0) {
  return Amount{}, InvalidNumberError{"Amount.Mul", n}
}
```

Is this intentional, or a bug?

**Comment by ericlagergren** [comment]
Interesting! I assume NaN is incorrect, but I’ll need to double check the GDA spec first.

**Comment by ericlagergren** [comment]
The GDA spec says:

> The result of attempting to convert a string which does not have the syntax of a numeric string is [0,qNaN].

http://speleotrove.com/decimal/daconvs.html#reftonum

Admittedly that’s unfortunate. Returning false sounds like it should be the correct behavior, even if it returns (NaN, false). I’ll see what I can do.

**Comment by Trial97** [comment]
Hi @ericlagergren,

Is there any news regarding this?
Also is the NaN check intended after SetString to see if the decimal.Big was set correctly?

Thanks,
Trial97

**Comment by ericlagergren** [comment]
The NaN check is to see if the result is NaN, which is a valid GDA decimal.

But like I mentioned before, the library should be updated so that

   SetString("invalid") // NaN, false
   SetString("NaN") // NaN, true

Ultimately, though, you'd still have to check if the result is NaN. A user could pass "NaN" instead of "3,60".

**Comment by ericlagergren** [comment]
You'll want to check the conditions: https://github.com/ericlagergren/decimal/issues/166#issuecomment-949468326
