### ISSUE TITLE
Float64()

### ISSUE THREAD

**Issue by rif** [ericlagergren/decimal#18]
Is a method like (*Big) Float64() float64 out of the question?
I would use that mostly for formatting using strconv.FormatFloat(). Currently to use that I would use String() than ParseFloat than FormatFloat.
Is there an easier workaround?

**Comment by ericlagergren** [comment]
`Float64` is on my todo list, although in your case it seems you might benefit from a `FormatFloat(x *Big, fmt byte, prec, intSize int) string` function. How are you formatting the float?

**Comment by rif** [comment]
sometimes I need a fixed number of digits after the decimal point e.g. 0.01 as 0.0100

**Comment by ericlagergren** [comment]
I think I could solve that problem by finishing https://github.com/ericlagergren/decimal/blob/c37ac6f12cd2136615dee587edb8acd75f8e3271/decimal.go#L466

**Comment by rif** [comment]
I'll be grateful for any solution you provide :) (I am sure it will be better than what I am doing right now)

**Comment by ericlagergren** [comment]
Update: I am partway through a fmt.Formatter solution so you can format decimals with fmt.Sprintf

**Comment by ericlagergren** [comment]
Hi, I know it's been a while but fmt.Formatter has been merged :-)
