### ISSUE TITLE
Benchmarks add unnecessary dependencies

### ISSUE THREAD

**Issue by lotodore** [ericlagergren/decimal#181]
Due to dependencies to shopspring decimal etc. in the benchmarks folder, this decimal library adds dependencies to these additional libraries to go.sum.
IMHO this is not a good idea, these dependencies are not required for "normal usage". Also, they cause licensing issues.

I would formally need to add shopspring decimal MIT license to my application if I use this decimal library, because it is a dependency.

Might it be possible to move benchmarks to a different project?

**Comment by ericlagergren** [comment]
@lotodore would you mind sending a PR?

**Comment by lotodore** [comment]
I cannot create a new github project in a pull request, but I've submitted a pull request which (to my knowledge) prepares everything.

**Comment by ericlagergren** [comment]
et voila https://github.com/ericlagergren/decimal_benchmarks

**Comment by lotodore** [comment]
Thanks. Should I directly add the files there?

**Comment by ericlagergren** [comment]
Yes, please!

**Comment by lotodore** [comment]
Fixed by https://github.com/ericlagergren/decimal/pull/183
