### ISSUE TITLE
Negative Cmp

### ISSUE THREAD

**Issue by rif** [ericlagergren/decimal#19]
I have this new issue, Cmp should return -1, right?
```go
func TestCmpNeg(t *testing.T) {
	x := New(-20102859, 6)
	y := New(-20, 0)
	if x.Cmp(y) != -1 {
		t.Errorf("error in cmp x=%v, y=%v, x.Cmp(y)=%v", x, y, x.Cmp(y))
	}
}
=> error in cmp x=-20.102859, y=-20, x.Cmp(y)=1
```

**Comment by rif** [comment]
Can I do something to help with this?

**Comment by ericlagergren** [comment]
yeah! If you want to tackle this I'd be much obliged. I haven't had a free moment to work on this yet, sorry. :/

**Comment by rif** [comment]
I was hoping that you'll realize quickly what the problem is as there are a lot of cases where negative numbers are not compared correctly, e.g. even if I go for -40(with scale) and -20

```go
func TestDecCmpNeg(t *testing.T) {
	x := NewVal(-40000000, 6)
	y := NewVal(-20, 0)
	if x.Cmp(y) != -1 {
		t.Errorf("error in cmp x=%v, y=%v, x.Cmp(y)=%v", x, y, x.Cmp(y))
	}
}
```
```
error in cmp x=-40, y=-20, x.Cmp(y)=1
```

**Comment by ericlagergren** [comment]
I use abscmp, that's why. derp.
