### ISSUE TITLE
Missing basic functionality

### ISSUE THREAD

**Issue by kostya-sh** [ericlagergren/decimal#2]
I believe the following basic functionality should be provided:
- [x] SetFloat(*big.Float)
- [x] Float() *big.Float
- [x] SetRat(*big.Rat)
- [x] Rat() *big.Rat
- [ ] `CmpTotal` - http://speleotrove.com/decimal/damisc.html#refcotot
- [x] fmt.Printf support (%s, %g, %f)

---
## From #5:

I think the library should provide the following functionality:

To String
- [x] String() - scientific string representation as per http://speleotrove.com/decimal/daconvs.html#reftostr
- fmt.Frintf support (https://golang.org/pkg/fmt/)
- [x] %e - scientific string (same as String())
- [x] %f - fixed string (with precision support, e.g. %.2f)
- [x] %g - %e or %f
- [x] %s - String()
- [x] %v - internal representation (unscaled value and scale)

From String
- [x] SetString(s string) - http://speleotrove.com/decimal/daconvs.html#reftonum
- [ ] fmt.Scanf support

**Comment by ericlagergren** [comment]
Will definitely add these.

**Comment by ericlagergren** [comment]
@kostya-sh would you be willing to work on implementing exp/decimal with me? You were very helpful with this implementation and I need an additional contributor before exp/decimal can be opened, so I figured I'd ask you first.

**Comment by kostya-sh** [comment]
Hi Eric,

I would love to help but realisticly I do not have much time right now.
Having said that I am still ok to review the code and maybe do some
testing.

Cheers,
Konstantin

**Comment by ericlagergren** [comment]
@kostya-sh Understood! If it's something you want to do (reviewing or testing or whatever you'd like) the CL is: https://go-review.googlesource.com/#/c/25146/

Also, thanks again for your earlier help, it was very much appreciated. :smiley:

**Comment by kostya-sh** [comment]
I have added a few comments to start with. I think it would be good to have a description of possible big.Decimal values and overview how result of all operations is rounded depending on context. Something similar to https://golang.org/pkg/math/big/#Float and https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html

Also I suggest to add @griesemer as a reviewer for this CL. He worked on math/big package and I hope will have interest in exp/decimal as well. As far as I know if you want to contribute to golang.org/x packages you have to find a reviewer from Google.

**Comment by ericlagergren** [comment]
Thank you for the comments, I'll have a look when I get into work today.

At first I assumed I needed a reviewer from Google, but adg simply said
"contributor" so I took that to mean anybody. I'm a bit confused.

Thanks for the griesemer@ suggestion.

**Comment by ericlagergren** [comment]
added specific issues for the remaining two. Thanks @kostya-sh
