### ISSUE TITLE
Error handling (panics, nan, inf)

### ISSUE THREAD

**Issue by kostya-sh** [ericlagergren/decimal#4]
I think that a library like decimal should never panic. Generally inputs can come from users (e.g. from an HTML form) and it is much nicer to have an ability to handle errors without using recover or pre-validating decimals before each operation.

Have a look at `math/big.Accuracy`, I think it is better to use it instead of `bool` or `error` where it makes sense. E.g. https://golang.org/pkg/math/big/#Float.Uint64

It might be good idea to introduce `+Inf` and `-Inf` values for Decimal objects. This gives natural way to report errors for many operations, such as multiplying two large numbers, division by 0, parsing something like `1e+908940390904920390109201902909201901`, etc.
- [x] Trade panics for `+/- Inf`
- [ ] Return something similar to `big.Accuracy`

**Comment by ericlagergren** [comment]
> I think that a library like decimal should never panic. 

I never felt good about the panics myself. They were in there primarily because I had not worked on incorporating `+/- Inf`, which leads me to...

> It might be good idea to introduce +Inf and -Inf values for Decimal objects.

Yes. I've been working on this tonight and am planning on following the IEEE 754 `Inf` rules much like the `math` package does.

**Comment by kostya-sh** [comment]
BTW, math/big.Float doesn't support NaN. There is https://golang.org/pkg/math/big/#ErrNaN instead. Probably your library should use the same approach.

**Comment by ericlagergren** [comment]
Yeah. I'm curious how I'd handle cases like -Inf + -Inf where (to my
knowledge) IEEE dictates the result should be NaN.

I'd like to get away from NaN, though, since +/- Inf should be good enough
(I think).

**Comment by kostya-sh** [comment]
From https://golang.org/pkg/math/big/#Float.Add:

> Add panics with ErrNaN if x and y are infinities with opposite signs. The value of z is undefined in that case.

**Comment by ericlagergren** [comment]
I wonder if it's worth adding traps to the Context so the user can decide
whether they want to have quiet or signaling NaN.

There could be a flag (defaults to signaling?) that determines the behavior
of operations that result in NaN.

**Comment by ericlagergren** [comment]
I do not think I want to implement `Accuracy`. I'm not quite sure what benefit it adds, tbh.
