### ISSUE TITLE
Benchmarks PI add github.com/shopspring/decimal

### ISSUE THREAD

**Issue by SchumacherFM** [ericlagergren/decimal#40]
Hey Eric,

would love to see github.com/shopspring/decimal as an additional comparison in the PI benchmark.
I've tried it myself ... but failed :-(

Thanks, Cyrill

**Comment by ericlagergren** [comment]
Done, thanks for the suggestion.

**Comment by SchumacherFM** [comment]
Thanks! Very interesting how slow shopspring is. Makes me to favor your package.
