### ISSUE TITLE
Round to a different scale?

### ISSUE THREAD

**Issue by rdingwall** [ericlagergren/decimal#44]
Hello! Apologies if this is a very basic question, but I'm writing a financial application and trying to use `decimal.Big` to round an amount $0.009 to the nearest whole penny ($0.01). In this case the precision stays the same (1) but the scale changes (from 3 to 2).

```
v, _ := decimal.New(0, 0).SetString("0.009") // 0.009, scale 3, precision 1

v.Round(something) // 0.01, scale 2, precision 1
```
I'm not quite sure how to achieve this because [big.Round()](https://godoc.org/github.com/ericlagergren/decimal#Big.Round) only takes a parameter `n` for the new desired precision (which cannot be zero or negative).

Am I being terribly stupid here?

**Comment by ericlagergren** [comment]
Boom! No, you weren't being stupid. Unfortunately, I had neglected to add `Quantize` which basically means "give me N decimal places." But, here you are. Thanks for prompting me—it had been on my TODO list but should've been higher.

**Comment by cakey** [comment]
@ericlagergren Awesome! I was literally looking for this last week :) Thank you!

**Comment by rdingwall** [comment]
Amazing! Thank you @ericlagergren! 😃

**Comment by ericlagergren** [comment]
@cakey @rdingwall cheers. BTW I just pushed a quick update: I had the signs for the input to `Quantize` backwards. So, now `Quantize(2)` means 2 digits after the radix, not -2.

v3.0 which will codify all this will be out soon ish. Few performance issues to fix first.
