### ISSUE TITLE
SetMantScale doesn't set compact when value == 0

### ISSUE THREAD

**Issue by kdar** [ericlagergren/decimal#51]
This bit of code prints out 1 because compact is still set to 1.

```
d := decimal.New(1, 0)
d.SetMantScale(0, 0)
fmt.Println(d)
// 1
```

**Comment by ericlagergren** [comment]
Don't worry, it's just a printing bug. Thanks for letting me know. :-)

**Comment by ericlagergren** [comment]
fixed in https://github.com/ericlagergren/decimal/commit/bc5a2dfe4cb4ce5c42bfb557eda3f5a894704e33
