### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by tapir** [ericlagergren/decimal#56]
Is this package considered stable?

```Go
..\..\..\github.com\ericlagergren\decimal\big.go:765: xb.IsInt64 undefined (type *big.Int has no field or method IsInt64)
```

**Comment by tapir** [comment]
Looks like due to go 1.8.1 I've upgraded to 1.9.2 and the problem is gone.
Maybe there should be something on the Readme that says the minimum required Go version is 1.9?

Thanks closing this now

**Comment by ericlagergren** [comment]
ah, yeah. I've been meaning to update the readme to mention that I only plan on supporting the versions Go does. thank you for reminding me.
