### ISSUE TITLE
String() method is slow

### ISSUE THREAD

**Issue by tapir** [ericlagergren/decimal#57]
I've been using shopspring/decimal until now and I've recently switched to this one. Quick benchmarks show that my apps arithmetic related methods just got faster 3 times. (Thanks!) However after all the operations are finished I'm writing this data in bulk to an SQL database and at that point conversion to string via big.String() is 2 times slower compared to shopspring's decimal library.

Is there a quick fix? I've been thinking if there was an easy way to extract the numbers after and before the decimal point, it would be quite fast to form something like "-xx.yyy" but couldn't find such functionality.

thanks

**Comment by ericlagergren** [comment]
Do you have some benchmarks I could look at? Or at least some examples of the types of decimals you're using. The to/from string code hasn't been optimized very much, so it's something I should look into.

**Comment by tapir** [comment]
After a long time of not being able tor reproduce this I've noticed that it was actually due to a bug on my code. Closing, thanks very much
