### ISSUE TITLE
Question about quantize and rounding modes

### ISSUE THREAD

**Issue by tapir** [ericlagergren/decimal#58]
I'm trying to understand the Banker's round mode and how quantize() works. Below is my example
```go
package main

import "github.com/ericlagergren/decimal"
import "fmt"

func main() {
	x := decimal.WithContext(decimal.Context{
		OperatingMode: decimal.Go,
		Precision:     24,
		RoundingMode:  decimal.ToNearestEven,
		Traps:         ^(decimal.Inexact | decimal.Rounded | decimal.Subnormal),
	})
	x.SetFloat64(2.335)
	fmt.Println(x.Quantize(2))
	x.SetFloat64(2.325)
	fmt.Println(x.Quantize(2))
}
```
I would expect this to produce 
```
2.34
2.32
```
but instead I get
```
2.33
2.33
```

Is this expected? Am I missing something?

Thanks

**Comment by ericlagergren** [comment]
It's how `SetFloat64` interprets its input. Base-2 floating-point numbers (`float64`, etc.) cannot exactly represent all numbers. To see what I mean, try this

    y := 2.335
    fmt.Printf("%.24g\n", y)
    x.SetFloat64(2.335)
    fmt.Printf("%g\n", x)

There's really no way around this. If you want exact inputs you'll either need to use `SetString`, `SetMantScale`, etc.

With respect to the difference between `Quantize` and `Round`:

`Quantize` rounds down to `n` digits after the radix.
`Round` rounds down to `n` significant digits (i.e., digits of _precision_)

**Comment by tapir** [comment]
understood thanks
