### ISSUE TITLE
.Rat() bug when exp > 0

### ISSUE THREAD

**Issue by cakey** [ericlagergren/decimal#65]
Hey!
Great library!

Unless I'm misunderstanding, I believe there's a bug in .Rat() (or perhaps .SetRat breaks internal assumptions):

```
expected := "999999999000000000000000000000"
r, _ := new(big.Rat).SetString(expected)
dec := new(decimal.Big)
dec.SetRat(r)
decString := dec.String()
actual := dec.Rat(nil).String()
fmt.Println("expected:", expected)
fmt.Println("decString:", decString)
fmt.Println("actual:", actual)
```
```
expected: 999999999000000000000000000000
decString: 9.999999990000000E+29
actual: 9999999990000000/1
```
Basically it seems like the numerator isn't being scaled properly when exp > 0

However it works correctly if I directly .SetString() on the decimal.Big because the exp is 0 rather than 14.

Thanks,
Ben

**Comment by ericlagergren** [comment]
You’re right. Sorry about that.

**Comment by ericlagergren** [comment]
(Also, thanks for the compliment! I was replying on my phone, thus the brevity.)

I'll be pushing a fix for this bug soon.

**Comment by cakey** [comment]
Awesome! Your response times are very very appreciated! Let me know if I can help out at all :)

**Comment by ericlagergren** [comment]
Off the top of my head:

- there's plenty of TODOs in the code. (`git gret -E "TODO"`)
- there's one issue about the ugly `math.Pow` code
- there are a few routines in `parity.md` that I haven't implemented yet
- better tests (even though I'm satisfied with the tests I have right now)

But all those are kinda boring, tbh.

What would be great to know is what you use the library for. I've wanted to make a list of people/projects who use it, partially for my amusement but also so people know the project _actually_ gets used in production (or for fun).

**Comment by ericlagergren** [comment]
https://github.com/ericlagergren/decimal/commit/7cf4cd4305767abe571e1ebef1481afef6fc1dbb

**Comment by cakey** [comment]
Awesome, thank you!

Our use case is a read only analytical database. We're evaluating a number of faster alternatives to using big.Rat, which has poor performance as we've started to introduce numerically intensive functionality. (Previously with most of the expensive calculations around filtering/grouping etc, we've been able to stick with int64)
