### ISSUE TITLE
Could you add LICENSE file?

### ISSUE THREAD

**Issue by hnakamur** [ericlagergren/decimal#7]
First of all, thanks for creating and sharing a nice software!

Could you add LICENSE file?
The following page may help for choosing a licnese.
[Choose an open source license - Choose a License](http://choosealicense.com/)

I hope you choose a permissive license like MIT or Apache.
Thanks!

**Comment by ericlagergren** [comment]
License got deleted by accident. It used to be (and still is) BSD. Proof: https://github.com/EricLagergren/decimal/blob/2a8092a629d1e90338cbca74ecf31a15ee192843/LICENSE

I'll add it in later. I'm working on some changes right now including a couple bug fixes. Haven't had much free time lately, sorry.

**Comment by hnakamur** [comment]
Thanks!
