### ISSUE TITLE
math: Sqrt incorrectly rounds down to the ideal exponent if ideal != precision and perfectSquare

### ISSUE THREAD

**Issue by cakey** [ericlagergren/decimal#75]
Looks like it thinks it's a perfect square (sqrt(5.76)==2.4) and so incorrectly rounds it.

```
d2, _ := new(decimal.Big).SetString("5.76")
out2 := new(decimal.Big)
decmath.Sqrt(out2, d2)
fmt.Println(out2)
```

```
> 2
```

Not ideal  :)

**Comment by ericlagergren** [comment]
Probably just need to call `Reduce` instead of `Round`. How'd you catch this?

**Comment by cakey** [comment]
Failed a bunch of our internal tests

**Comment by ericlagergren** [comment]
Ugh, sorry about that.
