### ISSUE TITLE
Int64 doesn't handle lower bound properly

### ISSUE THREAD

**Issue by cakey** [ericlagergren/decimal#76]
```
d := new(decimal.Big).SetRat(new(big.Rat).SetInt64((math.MinInt64)))
fmt.Println(d.Int64())

d2 := new(decimal.Big).SetRat(new(big.Rat).SetInt64((math.MinInt64 + 300)))
fmt.Println(d2.Int64())

d3 := new(decimal.Big).SetRat(new(big.Rat).SetInt64((math.MinInt64 + 350)))
fmt.Println(d3.Int64())
```

```
> 0 false
> 0 false
> -9223372036854775000 true
```

Unless I'm misunderstanding, all 3 should return true?

It looks like it's triggering the `u > math.MaxInt64` branch.

I imagine it might be something related to .compact being uint64, but here we care about int64, but I haven't dived in too deep.

I realised it might have something to do with the set precision - if i set precision high enough, then   math.MinInt64+1 works correctly, but never math.MinInt64.

Is this intended behaviour?

**Comment by ericlagergren** [comment]
You're correct about precision. Your call to `SetRat` rounds down based on `z`'s `Context`. (Essentially, `SetRat` is computed as `z = a / b` where `a` and `b` are the numerator and denominator of `x`, respectively.)

You're also correct that branch doesn't take into consideration that the negative half of a 64-bit integer is +1 larger than the positive half.

**Comment by ericlagergren** [comment]
Okay. That's fixed. I'm gonna push up a 3.1 which has a handful of bug fixes once Travis CI green lights me. Thanks for reporting them. Your issue made me curious: do you need something like `Context.SetRat`? I've omitted `Context` versions of most of the `SetX` methods, but I'm not opposed to adding them.
