### ISSUE TITLE
math: add Floor and Ceil functions

### ISSUE THREAD

**Issue by Eun** [ericlagergren/decimal#79]
Hey there,
first of: great work 👍

I noticed that there are no Floor or Ceil functions.

Are there any plans to include them?

**Comment by ericlagergren** [comment]
Thanks!

They’re not a part of the GDA spec so I haven’t added them yet. I’m open to adding them. 

Until I (or somebody else) does, you can simulate them:

    func floor(z *decimal.Big) *decimal.Big {
        return z.Quantize(0)
    }

    func ceil(z *decimal.Big) *decimal.Big {
        return z.Neg(floor(z.Neg(z)))
    }

I *think* that should work but I haven’t tested it.

**Comment by ericlagergren** [comment]
(Keep in mind Neg possibly rounds and I’m not entirely sure if floor is correct for negatives. I’ll look more into it later.)

**Comment by Eun** [comment]
Thanks for your quick response,

however the code you provided does not work.
Floor is wrong, therefore ceil is too.

Here is a simple test code:
```go
func TestStdFloor(t *testing.T) {
	require.Equal(t, float64(2), math.Floor(2))
	require.Equal(t, float64(2), math.Floor(2.4))
	require.Equal(t, float64(2), math.Floor(2.5))
	require.Equal(t, float64(2), math.Floor(2.9))
	require.Equal(t, float64(-3), math.Floor(-2.7))
	require.Equal(t, float64(-2), math.Floor(-2))
}

func TestStdCeil(t *testing.T) {
	require.Equal(t, float64(2), math.Ceil(2))
	require.Equal(t, float64(3), math.Ceil(2.4))
	require.Equal(t, float64(3), math.Ceil(2.5))
	require.Equal(t, float64(3), math.Ceil(2.9))
	require.Equal(t, float64(-2), math.Ceil(-2.7))
	require.Equal(t, float64(-2), math.Ceil(-2))
}
```

**Comment by nathanhack** [comment]
You could try this:

```

func floor(z *decimal.Big) *decimal.Big {
	ctx := decimal.Context{Precision: z.Context.Precision}
	if z.Signbit() {
		ctx.RoundingMode = decimal.AwayFromZero
	} else {
		ctx.RoundingMode = decimal.ToZero
	}
	return ctx.RoundToInt(z)
}

func ceil(z *decimal.Big) *decimal.Big {
	ctx := decimal.Context{Precision: z.Context.Precision}
	if z.Signbit() {
		ctx.RoundingMode = decimal.ToZero
	} else {
		ctx.RoundingMode = decimal.AwayFromZero
	}
	return ctx.RoundToInt(z)
}

```

**Comment by ericlagergren** [comment]
Yeah, that'll probably get the signs right. IIRC, `ceil = -floor(-x)` so that might simplify things.

I should get around to working on it this upcoming week, I think.

**Comment by Eun** [comment]
@nathanhack that works thanks 👍

**Comment by ericlagergren** [comment]
Neat, both are added now. @nathanhack thanks for the `Floor` suggestion.
