### ISSUE TITLE
Formatting to a fixed width

### ISSUE THREAD

**Issue by OpinionatedGeek** [ericlagergren/decimal#80]
Hi,

Let's say I have a bunch of numbers to 10 decimal places, and I wanted to print them out to a fixed width, so that if for example the number had only 9 decimal places, it had a trailing zero. Like:

0.1234567891
0.1234567892
0.1234567890 < this one has a trailing zero

I can achieve this with a float64 using the format string "%.10f\n".

Unfortunately I can't see how to do it using this library. Am I doing something wrong?

The docs say 'Given %f, precision is the number of digits following the radix.' so I'd expect "%.10f\n" to work the same way for both float64 and decimal.Big. It doesn't though - no trailing zeros are added.

Here's a simple program to show you what I mean:

```
package main

import (
	"fmt"

	"github.com/ericlagergren/decimal"
)

func testPrint(floatValue float64, decimalValue *decimal.Big) {
	fmt.Printf("F: %.10f\n", floatValue)
	fmt.Printf("D: %.10f\n", decimalValue)
}

func main() {
	testDecimal, _ := new(decimal.Big).SetString("0.1234567891")
	testPrint(0.1234567891, testDecimal)
	testDecimal, _ = new(decimal.Big).SetString("0.123456789")
	testPrint(0.123456789, testDecimal)
	testDecimal, _ = new(decimal.Big).SetString("0.123")
	testPrint(0.123, testDecimal)
}
```
And here's the output:
F: 0.1234567891
D: 0.1234567891
F: 0.1234567890
D: 0.123456789
F: 0.1230000000
D: 0.123

As you can see, the 'D' lines truncate rather than adding trailing zeros.

Have I misunderstood something?

**Comment by ericlagergren** [comment]
Looks like an issue that cropped up when I changed an internal representation of the exponent a while back.

**Comment by ericlagergren** [comment]
Thanks for letting me know and sorry about the issue!

**Comment by OpinionatedGeek** [comment]
Wow - thanks for the fix and the fast turnaround!
