### ISSUE TITLE
Feature request remove/change unsafe code

### ISSUE THREAD

**Issue by nathanhack** [ericlagergren/decimal#82]
The internal/buf/buffer.go has usage for unsafe. It's the only file using unsafe, would you consider removing/changing the unsafe. That way, it should make the library safe to use with gopherjs - because it would be a golang only implementation.

**Comment by ericlagergren** [comment]
@nathanhack Yeah, I'll put it behind a build tag. Should've done that in the first place, although it's basically a boring implementation of `strings.Builder` which also uses unsafe.

**Comment by ericlagergren** [comment]
Is there a convention that gopherjs uses? Like `// +build safe`? Or `// +build unsafe`?

**Comment by ericlagergren** [comment]
Nvm, found it. https://github.com/golang/go/issues/23172

**Comment by nathanhack** [comment]
Thank you!
