### ISSUE TITLE
Formatting and rounding of very small numbers

### ISSUE THREAD

**Issue by OpinionatedGeek** [ericlagergren/decimal#83]
Hi,

This is a continuation of [Issue 80](https://github.com/ericlagergren/decimal/issues/80) - I'm afraid it won't let me re-open that one.

Formatting of very small numbers doesn't seem to follow the right path. I've updated my test program from the previous issue to show you what I mean.
```
package main

import (
	"fmt"

	"github.com/ericlagergren/decimal"
)

func testPrint(floatValue float64, decimalValue *decimal.Big) {
	fmt.Printf("F: %.10f\n", floatValue)
	fmt.Printf("D: %.10f\n", decimalValue)
}

func main() {
	testDecimal, _ := new(decimal.Big).SetString("0.1234567891")
	testPrint(0.1234567891, testDecimal)
	testDecimal, _ = new(decimal.Big).SetString("0.123456789")
	testPrint(0.123456789, testDecimal)
	testDecimal, _ = new(decimal.Big).SetString("0.123")
	testPrint(0.123, testDecimal)
	testDecimal, _ = new(decimal.Big).SetString("0.0000000000000000000000000000000000000000000000000000000000001")
	testPrint(0.0000000000000000000000000000000000000000000000000000000000001, testDecimal)
}
```
This outputs:
```
F: 0.1234567891
D: 0.1234567891
F: 0.1234567890
D: 0.1234567890
F: 0.1230000000
D: 0.1230000000
F: 0.0000000000
D: 0.0000000000000000000000000000000000000000000000000000000000001
```

As you can see, the last line doesn't follow what I'd expect for a %.10f format. I'd expect the number to be rounded to 10 decimal places, which in this case would round to zero.

Have I misunderstood something?

Many thanks,

Geoff

**Comment by ericlagergren** [comment]
Yeah, sorry about that. Turns out I had to rework more of `Format` than I thought. It needs to be tested better. There aren't many tests for `Format` because generating them is a bit difficult. Should put that on my TODO list :)
