### ISSUE TITLE
.SetFloat64() has incorrect results.

### ISSUE THREAD

**Issue by cakey** [ericlagergren/decimal#89]
Again, forgive me if I've overlooked something
```
f := 8e+19
b := new(decimal.Big)
b.Context.Precision = 9999
b = b.SetFloat64(f)
fmt.Println(b.String())

>>> 6213023705161793536
```

**Comment by ericlagergren** [comment]
Nah, that's right. It's fine if I remove the 

`if s := uint(-shift); s < 64 { ... }` 

branch and just use `big.Int` it works. But, only for some ranges of numbers. Like [8e+19, 8e3X] doesn't work. ¯\\\_(ツ)_/¯
