### ISSUE TITLE
"suite" tests

### ISSUE THREAD

**Issue by madelynnblue** [ericlagergren/decimal#9]
There are many tests in the suite directory. But I can't find where they are actually tested. Was your work there preliminary?

Also what are your thoughts on http://speleotrove.com/decimal/ which appears to be a similar project from IBM, but with other coverage?

**Comment by ericlagergren** [comment]
preliminary, yes. suite/ is working, but I've yet to write tests that utilize that sub package yet.

Speletrove's decimal library is similar, yet different. He outlines several different types and I try to model my library after his spec (http://speleotrove.com/decimal/decarith.html) without following a particular implementation.
