### ISSUE TITLE
Neg() doesn't behave properly when number is negative

### ISSUE THREAD

**Issue by aarondl** [ericlagergren/decimal#90]
Version: 3.1 tag

```go
package main

import (
	"fmt"

	"github.com/ericlagergren/decimal"
)

func main() {
	x := decimal.New(10, 0)
	fmt.Println(x)
	x.Neg(x)
	fmt.Println(x)
	x.Neg(x)
	fmt.Println(x)
	x.Mul(decimal.New(-1, 0), x)
	fmt.Println(x)
}
```

Given this sample application I expected to see output:

```text
10
-10
10
-10
```

But I see the output:

```text
10
-10
-10
10
```

It seems like `Neg()` is failing to set `x` to `-x` when `x` is already negative.

**Comment by ericlagergren** [comment]
ah yeah, that's fixed on head. I should push a v3.2. There's enough fixes to warrant it, imo.

**Comment by ericlagergren** [comment]
Okay, it's official: https://github.com/ericlagergren/decimal/releases/tag/v3.2
