### ISSUE TITLE
Quantize unexpected results

### ISSUE THREAD

**Issue by cakey** [ericlagergren/decimal#91]
Hey!

Am I misunderstanding what quantize is meant to do?

```

	c, _ := decimal.WithContext(decimal.Context32).SetString("900000")
	fmt.Printf("c: %s\n", c.Quantize(2))

	d, _ := decimal.WithContext(decimal.Context32).SetString("9")
	fmt.Printf("d: %s\n", d.Quantize(7))
```

```
c: NaN7
d: NaN7
```

I wouldn't have expected NaNs in these cases.

Also unrelated, but I was putting together a PR for the 1.9 branch, and I was having trouble with go test. Are some of the tests slow?

**Comment by ericlagergren** [comment]
Quit breaking my library.

Just kidding. :) I appreciate your help. Yes, some tests are slow. Run it with `-short` if you don't have over an hour to kill waiting for it to do stuff like test every 32-bit float. (Yes, I know it sounds silly but why not?) `-short` also skips a couple tests that allocate huge amounts of memory.

**Comment by ericlagergren** [comment]
Also, wrt to your original question: it's the proper behavior.

```
$ python3
Python 3.6.4 (default, Mar  6 2018, 19:03:35)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from decimal import *
>>> d=Decimal
>>> a=d('9')
>>> getcontext().prec=7
>>> a.quantize(d('0.0000001')) # same as d.Quantize(7) in Go
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
>>>
```

**Comment by ericlagergren** [comment]
Admittedly, it's somewhat surprising. But the spec requires a NaN result if the quantization exceeds the working precision.

For example, in the latter case you've set your working precision to 7 (via `Decimal32`), but the end result of the quantization would be `9.0000000`, which has 8 digits of precision.

The relavant part of the spec:

>  Unlike other operations, **if the length of the coefficient after the quantize operation would be greater than precision then an Invalid operation condition is raised.** This guarantees that, unless there is an error condition, the exponent of the result of a quantize is always equal to that of the right-hand operand.

**Comment by cakey** [comment]
Appreciate the quick response as always! :)

I think I was doing something like (9e+25).quantize(-5) with precision 18, and was very confused that it was returning a NaN, but your explanation makes sense.

**Comment by ericlagergren** [comment]
Yep. The GDA has lots of rough edges, mostly because math has lots of rough edges.
