### ISSUE TITLE
ORM Integration

### ISSUE THREAD

**Issue by aarondl** [ericlagergren/decimal#95]
Hey @ericlagergren.

Finally getting around to wanting to integrate this into our "orm" (https://github.com/volatiletech/sqlboiler) as the decimal library of choice.

Wanted to talk to you about a few small things though. We have two problems that we need to deal with coming from the sql world. And then I've a random question for you.

1) Scanner/Valuers. This you've obviously tackled for postgres, we only support 3 databases out of the box (psql, mysql, and mssql). I don't think it's that important to do bounds checking and what-not in code since the database should puke errors if it can't do something (although mysql being the clown truck that it is very likely just truncates values -_-). I'm wondering if we could create a generic implementation that's not specific to any one database.

2) Nullable: Unfortunately in the sql model that we have today, nullable types are typically represented by a separate type that includes a "null" flag. Although some people use a pointer to allow nulls we decided to follow the standard library model and create NullX types for all the types that we use. It appears that there's no nullable Decimal type, do you think that's something we could add to this library? If that's something you're not interested in we'll have to wrap the decimal type in our code and it's just less pretty :p

3) Looking at the way you've wrapped the type in the psql code, it seems to wind up requiring a reference to `.V` and all the operations are done on that. I suppose it's impossible to avoid since the API relies on assigning values all the time. Was just looking for thoughts on potentially avoiding the following (although it probably wouldn't work regardless since we never put pointers to anything on our generated structs):

    ```go
    user.Money.V.Mul(...)
    ```

Thanks for your time! Also thanks for fixing that bug I reported a few months back, that was a bit surprising :)

**Comment by ericlagergren** [comment]
Hey!

1. That should be fine. `sql/generic`? I added the manual bounds checking since I figured it'd be nice to preemptively avoid a trip to the database, or at least round the decimals to the proper size beforehand. Not sure whether that was a good idea or not.

2. A `NullDecimal` should be fine in `sql/generic`. I'm not sure how to handle this case

```
type NullDecimal {
    *decimal.Big
    Null bool
}
[ ... ]
db.Exec("INSERT ... ", NullDecimal{Big: nil, Null: false}) // zero values added for clarity
```

The first thing that pops into my head is letting it be equal to "0". Do you know what other NullX implementations do where X is a pointer?

3. I don't recall why I didn't embed the decimal. For (2) the decimal can just be embedded. Is your `Money` type going to be `type Money struct { NullDecimal }` or what?

**Comment by aarondl** [comment]
`sql/generic` sounds fine.

I think that it's best to let the database deal with the restrictions on the types. Consider if you move from one version of the DB to the next, and something's changed. The library now needs to be updated, but there's almost no way of knowing that the database has changed. Or even supporting two users on different versions of said database. It's also possible to get it wrong from misreading/lacking documentation. You also now do a needless check 2x on a proper value, and most of the time it's a proper value so you're penalizing performance on the normal path and optimizing for an error case which would be infrequent. Just my 2c about duplicating DB constraints as someone who had to make the same choices :)

I don't think we actually have anything that requires it to be a pointer. We count on the zero value being usable. If we were to embed the decimal type as a not-pointer it's going to make it awfully inconvenient to use isn't it? :\ If I'm right then it'd go something like this:

```go
// square money
myStruct.Money.Big = *myStruct.Money.Mul(&myStruct.Money.Big, &myStruct.Money.Big)
```

In the case of null structs, the zero value is a null value. See the standard library for an example of how it's implemented: https://golang.org/pkg/database/sql/#NullBool This is the pattern we've used for all of our types.

The structs would look like:
```go
type User struct {
   Money generic.Decimal
}
```

Thoughts?

**Comment by aarondl** [comment]
Hey @ericlagergren. Quick friendly ping as we're nearing the release of v3 and need to sort this out. I also have a contributor that jumped in without knowledge of our conversation here to try and finish this (which is awesome) so I've asked him to review the details here.

He's the author of https://github.com/ericlagergren/decimal/pull/98

**Comment by ericlagergren** [comment]
Ack. If you or the contributor want to submit a PR, that’s awesome.
Otherwise, I’ll create one by the end of the week I think.

**Comment by aarondl** [comment]
Happy no matter who does the work. Was just trying to figure out how to manage syntactically with all the pointers flying around. For example I wonder if we don't have a pointer on the User struct as above if json won't encode or what have you.

**Comment by ericlagergren** [comment]
I don’t think it would, even if it’s addressable since it’s hidden behind
an interface.

**Comment by aarondl** [comment]
https://play.golang.org/p/54m4rRQCsmZ

So I was messing around a bit on the playground with how this might look. It seems if we don't use pointers anywhere, it's actually kinda okay.

Though it seems odd at first glance that `MarshalText()` on big takes a pointer. Is there a reason for this? Just a big object I guess (pun intended)?

Anyway, this is about how we'd like to use it. I'm wondering if you could take a good look and point out maybe how it might be incompatible or painful for our users. It doesn't look super fun, but it looks doable?

**Comment by ericlagergren** [comment]
Yeah, it's a pointer for symmetry*, performance**, and safety***. Ordinarily it wouldn't be a pointer.

The only downside to embedding it without a pointer is how tedious it is to write

`a.Money.Mul(&a.Money, &b.Money)`

The only way to make it nicer would be to embed a pointer (only drops 1 character) or to write/generate wrapper methods.

Too bad the package wasn't designed around an interface

```
type Decimal interface {
    Add(x, y Decimal) Decimal
    [ ... ]
}
```
It would've made your situation much simpler ;)

*: You see the same thing in math/big.
**: It's something 76 bytes (ignoring padding), which isn't _horrendous_.
***: Accidentally copying the internal big.Int could be dangerous, same reason why bytes.Buffer only has pointer methods.

**Comment by aarondl** [comment]
Hey there @ericlagergren. I had a branch all ready to pull request when I suddenly realized that I needed to implement our "randomize" interface. It's an interface that creates a random value for sqlboiler. All of our custom types implement this but there's a problem... It requires importing 3 packages from sqlboiler -_-. Some interface huh? (There's one argument that wants the randomize package, /sigh. Why did I do this?). One day maybe I'll refactor that out but until then it made no sense to ask your library to depend on something insane like that in any way, so I opted to implement on our side.

The implementation is here. It has that nasty interface we spoke about but that's just how life is going to be. If people want they have the ability to replace this type with any type they want via our configuration file (so they could go to shopspring to get more bugs, less speed, but have that nicer interface).

https://github.com/volatiletech/sqlboiler/blob/v3/types/decimal.go

Any tips or advice for implementing or things I've missed please let me know. Also I found that there were times the database driver was giving me back a `float64`, how does the `postgres` type you made not deal with this case?

**Comment by ericlagergren** [comment]
Well dang! Perhaps some other time. I didn't see anything glaring in the code you linked. Whenever I've used postgres (via lib/pq) it've always received `DECIMAL` back as a string (or []byte, it's been a while since I've used it).

**Comment by MJacred** [comment]
> One day maybe I'll refactor that out

@aarondl: You already refactored the randomizing dependency out. So, can this issue be tackled again to integrate NullDecimal here?
