### ISSUE TITLE
Comparison results in wrong answer

### ISSUE THREAD

**Issue by timothyham** [ericlagergren/decimal#99]
This unit test fails:
```
func TestMul128(t *testing.T) {
	bad := &Big{compact: 11234567890123457890, exp: -20, precision: 20}
	ref := &Big{compact: 2, exp: -1, precision: 1}

	cmp := bad.Cmp(ref)
	if cmp != -1 {
		t.Errorf("expected %s smaller than %s\n", bad.String(), ref.String())
	}
	cmp = ref.Cmp(bad)
	if cmp != 1 {
		t.Errorf("expected %s larger than %s\n", ref.String(), bad.String())
	}
}
```

**Comment by timothyham** [comment]
Made a PR to fix this bug: https://github.com/ericlagergren/decimal/pull/100

**Comment by ericlagergren** [comment]
Hey, I ask this of everyone who creates an issue or PR—if you don't mind me asking, what're you using this library for? It's really cool to see the different ways people are using it.

Also, would you like your name and/or email listed as a contributor?

**Comment by timothyham** [comment]
My employer uses this library inside a business analytics application. Like many business applications, decimal math is important.

Sure, I'd love to have my name added to the contributor list :) Thx.
